# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='occupation',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
